```{r}
library(WikidataQueryServiceR)

mm = query_wikidata('SELECT ?cell_type ?cell_typeLabel (count(?marker) as ?marker_count)
WHERE 
{
  ?cell_type wdt:P31/wdt:P279* wd:Q189118.
  ?cell_type wdt:P703 wd:Q83310.
  ?cell_type wdt:P8872 ?marker. 
  SERVICE wikibase:label { bd:serviceParam wikibase:language "[AUTO_LANGUAGE],en". }
}
GROUP BY ?cell_type ?cell_typeLabel
')

hs = query_wikidata('SELECT ?cell_type ?cell_typeLabel (count(?marker) as ?marker_count)
WHERE 
{
  ?cell_type wdt:P31/wdt:P279* wd:Q189118.
  ?cell_type wdt:P703 wd:Q15978631.
  ?cell_type wdt:P8872 ?marker. 
  SERVICE wikibase:label { bd:serviceParam wikibase:language "[AUTO_LANGUAGE],en". }
}
GROUP BY ?cell_type ?cell_typeLabel')
```

```{r}

marker_count_mouse = data.frame(mm[,"marker_count"], "Mus musculus")
colnames(marker_count_mouse) = c("marker_count", "species")
marker_count_human = data.frame(hs[,"marker_count"], "Homo sapiens")
colnames(marker_count_human) = c("marker_count", "species")

marker_count = rbind(marker_count_human, marker_count_mouse)
marker_count
```

```{r}
library(ggplot2)

p <- ggplot(marker_count, aes(x=species, y=marker_count, colour = species)) +
  geom_jitter(width = 0.1, height = 0, alpha=0.7) +
  theme_classic() +
  scale_color_manual(values=c("purple", "darkorange")) +
  ylab("Number of markers per cell type") +
  xlab("Found in taxon") +
  theme(
  axis.title = element_text(size = 14),
  axis.text.y = element_text(size = 11),
  axis.text = element_text(size = 14, face = "italic")) + 
  theme(legend.position = "none")  +
  theme(
      axis.title.x = element_text(margin = unit(c(7, 0, 0, 0), "mm")),
      axis.title.y = element_text(margin = unit(c(0, 7, 0, 0), "mm"))
  )
  
ggsave(filename = "markers.pdf", p, height = 5, width = 5)
p
```


```{r}
cts = query_wikidata('SELECT ?cell1Label ?cell2Label
WHERE 
{
  ?cell1 wdt:P31 wd:Q189118.
  ?cell2 wdt:P31 wd:Q189118.
  ?cell1 wdt:P279 ?cell2.
  SERVICE wikibase:label { bd:serviceParam wikibase:language "[AUTO_LANGUAGE],en". }
}')
cts
```

```{r}
library(network)
library(sna)
library(igraph)
library(intergraph)
library(ggnetwork)
cts <- as.matrix(cts) #igraph wants our data in matrix format
ig_obj <- graph_from_edgelist(cts, directed=TRUE)


```
```{r}

nodes = vertex_attr(ig_obj, name="name")

species_vector = c()
species = ""

for (name in nodes)
{
  
  if (grepl("human", name, fixed = TRUE)){
    species = "Homo sapiens"
  } else if (grepl("mouse", name, fixed = TRUE)){
    species = "Mus musculus"
  } else {
    species = "none"
  }

  species_vector = c(species_vector, species)

}

```


```{r}
g <- ig_obj %>%
  set_vertex_attr("species", value = species_vector) 

net_obj <- intergraph::asNetwork(g)


n <- ggnetwork(net_obj, layout = "fruchtermanreingold", cell.jitter = 0.75)

p2 <- ggplot(n, aes(x = x, y = y, xend = xend, yend = yend)) +
  geom_edges(alpha=0.9) +
  geom_nodes(aes(color = species), alpha=0.9) +
  theme_blank()+
  scale_color_manual(values=c("purple", "darkorange","gray50"))

ggsave(filename = "cell_types.pdf", p2, height = 20, width = 20, limitsize = FALSE)
```

